name: Valgrind

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: sudo apt-get update; sudo apt-get install -y valgrind
      - name: configure
        run: echo 'include(Dart)' >> CMakeLists.txt && cmake -S . -B build_dir -Wdev -DCMAKE_BUILD_TYPE=Debug -DMEMORYCHECK_COMMAND_OPTIONS="--leak-check=full --track-origins=yes --error-exitcode=1"
      - name: build
        run: cmake --build build_dir --verbose
      - name: test
        run: ctest -DExperimentalMemCheck --output-on-failure .
        working-directory: build_dir
